spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HibernateTest
    username: root
    password: LuhaismyMan12
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
